### ISSUE TITLE
lts-mainline-longterm >=6.1.16 build failed

### ISSUE THREAD

**Issue by m1khal3v** [TuxInvader/focal-mainline-builder#40]
![Снимок экрана от 2023-03-13 09-18-27](https://user-images.githubusercontent.com/41085561/224623101-5c3557b2-4b68-44b6-bfff-e34845c34ecd.png)

**Comment by TuxInvader** [comment]
The builds are failing because the kernel build now requires rust packages which aren't available in Jammy, but they are being back-ported. The rust bindgen-0.56 package  is currently in [proposed](http://archive.ubuntu.com/ubuntu/pool/universe/r/rust-bindgen-0.56/). When that package makes it through to the universe repo I'll resubmit the latest kernel build.

This may be the end of the line for focal though.

**Comment by m1khal3v** [comment]
> The builds are failing because the kernel build now requires rust packages which aren't available in Jammy, but they are being back-ported. The rust bindgen-0.56 package is currently in [proposed](http://archive.ubuntu.com/ubuntu/pool/universe/r/rust-bindgen-0.56/). When that package makes it through to the universe repo I'll resubmit the latest kernel build.
> 
> This may be the end of the line for focal though.

Sadly. Does 5.15 now also require rust? I ask because from some version 5.15 on the focal stopped loading normally, the interface is there, but most of the peripherals do not work, because of this I had to switch to 6.1

**Comment by nullket** [comment]
Concerning focal the 5.15 kernel is officially supported via [hwe](https://ubuntu.com/kernel/lifecycle#support-20-04) so you do not have to build it your self or use the ppa

> This may be the end of the line for focal though.

Even for 6.1? Were some rust dependencies introduced in the change from 6.1.15 to .16?

**Comment by TuxInvader** [comment]
It looks like the bindgen package has arrived in jammy and 6.2.6 has had a successful build. 

WRT focal: the early versions of 6.2 were built without rust, so I've updated the script to back-out those dependencies on 6.2 kernels for focal, and 6.2.6 is building now. I'm not sure what this will mean for 6.3 and newer kernels. It's likely that focal users will have to stick on the latest longterm series of 6.1.x, because the 6.2 kernel will only have a short support period.

In any case Jammy is the current LTS and it's been out for almost 12 months, it's time to upgrade people ;-)

**Comment by TuxInvader** [comment]
> Concerning focal the 5.15 kernel is officially supported via [hwe](https://ubuntu.com/kernel/lifecycle#support-20-04) so you do not have to build it your self or use the ppa
> 
> > This may be the end of the line for focal though.
> 
> Even for 6.1? Were some rust dependencies introduced in the change from 6.1.15 to .16?

The 6.1 kernel is the release that added Rust support, but the rust dependencies in Ubuntu kernels were added in the 6.2.3/6.1.16 time frame, so 6.1.16+ is also failing. I can remove the rust dependency from the 6.1 series kernels, and track that LTS as the final focal kernel. All newer kernels are going to require rust.

**Comment by TuxInvader** [comment]
work-around in 75acf7599eb64f9dbffe3dd417a7bdeb7d7e0e1c

**Comment by m1khal3v** [comment]
> work-around in [75acf75](https://github.com/TuxInvader/focal-mainline-builder/commit/75acf7599eb64f9dbffe3dd417a7bdeb7d7e0e1c)

Looks simple. What are the pitfalls of this method?

**Comment by m1khal3v** [comment]
@TuxInvader I tried to build the image on the last version of builder and still get the following error on the launchpad:

```
The following packages have unmet dependencies:
 sbuild-build-depends-main-dummy : Depends: rustc-1.62 but it is not installable
                                   Depends: rust-1.62-src but it is not installable
                                   Depends: rustfmt-1.62 but it is not installable
                                   Depends: bindgen-0.56 but it is not installable
```

What am i doing wrong? 

https://launchpad.net/~m1khal3v/+archive/ubuntu/focal-6.1/+packages

**Comment by m1khal3v** [comment]
I'm trying to build because I can't install the version from your repository, it gives an error about incompatible dependencies linux-generic-6.01 and linux-headers-6.1.19-060119-generic

**Comment by TuxInvader** [comment]
It should be fixed now. The change to remove the rust dependencies broke the rename process.The 6.1.19 package should be fixed on my PPA too.

**Comment by TuxInvader** [comment]
This is still an issue. The bindgen-0.56 package has not made it into universe yet, and is still in proposed for Jammy. I may need to disable rust in jammy while we wait for it to progress through the verification process. Ubuntu bug is here: https://bugs.launchpad.net/ubuntu/+source/rustc-1.62/+bug/1993183

**Comment by m1khal3v** [comment]
@TuxInvader what happened with 6.1 builds for focal ?

![Снимок экрана от 2023-05-25 17-57-24](https://github.com/TuxInvader/focal-mainline-builder/assets/41085561/cb75bf45-1d44-4c28-8e9f-8b7ff3407e26)

**Comment by TuxInvader** [comment]
The Ubuntu repos aren't syncing the changes from mainline builds anymore so I had no working tags to checkout. I fixed the issue by adding support for kernel.org as a git source and applying the ubuntu `crack.bundle`. I need to update the docs and submit the changes to thise repo, but there are now images available.
